### ISSUE TITLE
paddlepaddle Related errors

### ISSUE THREAD

**Issue by dikubab** [PaddleEdu/OCR-models-PaddlePaddle#3]
Hello Author, I appreciate your work. When I tried it. There is an error.  Please hep how to solve [it.](url)

RuntimeError: (PreconditionNotMet) The third-party dynamic library (libcublas.so) that Paddle depends on is not configured correctly. (error code is libcublas.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:234)
  [operator < gaussian_random > error]

**Comment by xmy0916** [comment]
Make sure your paddlepaddle is available in the GPU environment：
```bash
import paddle
paddle.fluid.install_check.run_check()
```
The main reason for this error is that CUDA and cudnn versions do not match.
you can use:
- cuda:10.2 
- cudnn:7.6
- python:3.7

It's troublesome to re install CUDA environment. You can also choose to use docker image. Please refer to here：
[https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html)

If the environment is really not well installed, you can try the online code first. The link is here：
[https://aistudio.baidu.com/aistudio/projectdetail/1945560](https://aistudio.baidu.com/aistudio/projectdetail/1945560)

**Comment by dikubab** [comment]
Thank you for your quick response. I solved the issue with following 

export PATH=/usr/local/cuda-10.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

**Comment by xmy0916** [comment]
> Thank you for your quick response. I solved the issue with following
> 
> export PATH=/usr/local/cuda-10.0/bin${PATH:+:${PATH}}
> export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

good!
